const questions = [ 
  "¿Cuáles son algunas de tus diferentes identidades?",
  "¿Qué ritual tienes del que no te gustaría prescindir?",
  "¿Qué acontecimiento histórico te gustaría haber presenciado?",
  "¿Qué desventajas tendría tu vida personal si pasáramos de un sistema basado en el dinero a un sistema basado en la naturaleza?",
  "¿Cuáles son los límites de tu libertad personal?",
  "¿Cómo afrontas las contradicciones?",
  "¿Importa más tu felicidad individual que la felicidad colectiva de la gente que te rodea?",
  "¿Cuánta responsabilidad asumes por tus decisiones? ¿Es la misma para todas tus decisiones?",
  "¿Por qué la gente disfruta mirándose?",
  "¿Qué hace falta para que la gente recuerde cosas concretas?",
  "¿De dónde vienes y adónde quieres ir?",
  "¿En qué te gusta gastar dinero?",
  "¿Para qué necesita la gente el arte?",
  "¿Qué significa para ti 'divertirse'?",
  "¿Preferirías que la gente que te rodea fuera principalmente amable o principalmente inteligente?",
  "¿Te gustaría vivir en un mundo de honestidad radical?",
  "¿Qué reto te gustaría más afrontar?",
  "¿Qué le hace feliz?",
  "¿Qué es lo que más te gusta procrastinar?",
  "¿Qué harías con 10.000 euros antes de que dejaran de tener valor?",
  "¿Con qué te gustaría que te pagaran en vez de con dinero?",
  "¿Te gustaría ser famoso? ¿De qué manera?",
  "Antes de hacer una llamada telefónica, ¿ensaya alguna vez lo que va a decir? ¿Por qué?",
  "¿Qué sería un día perfecto para usted?",
  "¿Tiene una corazonada secreta sobre cómo morirá?",
  "Si pudiera cambiar algo de su educación, ¿qué cambiaría?",
  "Si pudieras despertarte mañana habiendo ganado una cualidad o habilidad, ¿cuál sería?",
  "Si pudiera hacer una pregunta sobre su futuro y obtener una respuesta, ¿cuál sería?",
  "¿Cuál es el mayor logro de tu vida?",
  "¿Qué es lo que más valoras en una amistad?",
  "¿Cuál es tu recuerdo más preciado?",
  "¿Cuál es tu recuerdo más terrible?",
  "Si supieras que vas a morir dentro de un año, ¿cambiarías tu forma de vivir?",
  "Rellena el espacio en blanco: me gustaría tener a alguien con quien compartir ___",
  "¿Cuándo lloraste por última vez delante de otra persona? ¿Solo?",
  "¿Qué es demasiado serio para bromear?",
  "Si murieras esta noche sin poder comunicarte con nadie, ¿qué es lo que más lamentarías no haberle contado a alguien? ¿Por qué no se lo has dicho todavía?",
  "Tu casa/habitación, con todo lo que posees, se incendia. Después de salvar a tu familia y a tus mascotas, ¿puedes salvar un objeto más de las llamas? ¿Cuál sería?",
  "¿Qué canción te hace querer bailar inmediatamente?",
  "¿Qué te hace reír siempre?",
  "¿Cuál es el mejor libro que has leído y por qué?",
  "¿Cuál es la mejor película que has visto y por qué?",
  "¿Cuál es tu lugar favorito de tu ciudad?",
"¿Qué ha sido lo más espontáneo que has hecho?",
  "¿Qué tres cosas te ponen inmediatamente de mal humor?",
  "¿Cuáles han sido tus vacaciones más emocionantes?",
  "¿Cuál es tu cita favorita?",
  "¿A quién envidias más y por qué?",
  "¿Cuál ha sido la lección de vida más útil que has aprendido recientemente?",
  "¿En qué piensa primero cuando piensa en su familia?",
  "¿Hay algo en lo que crea firmemente?",
  "¿Por qué estás agradecido hoy?",
  "¿Qué es lo que más te entusiasma en este momento?",
  "¿Qué virtud quieres exhibir mañana?",
  "¿Qué es lo que estás evitando?",
  "¿Cuáles fueron tus mayores victorias del día?",
  "¿Te has dado cuenta de algo importante hoy?",
  "¿Cuál es el mayor obstáculo para alcanzar tu próximo objetivo? ¿Por qué no estás trabajando hoy en ello?",
  "Si repitieras todas las acciones que has hecho hoy durante un año, ¿dónde acabarías? ¿Es éste el lugar en el que quieres estar?",
  "¿Cómo te gusta hacer felices a los demás?",
  "¿Qué harías con 1 millón de euros en efectivo ahora mismo?",
  "¿Tres libros que leerías el resto de tu vida?",
  "Si vivieras en un mundo, donde cada decisión que tomas, crea un nuevo universo paralelo: ¿Qué universos paralelos te gustaría más viajar?",
  "Imagina que entre la Vida y la Muerte visitas el lugar donde te has sentido más realizado y más seguro y hablas con la persona que más te ha ayudado a crecer en tu infancia: ¿En qué lugar estarías y con qué persona te encontrarías?",
  "¿A qué alimento le tienes más apego emocional? ¿Por qué?",
  "¿Cuál ha sido tu concierto favorito al que has asistido?",
  "Si pudieras probar cualquier trabajo durante un día, ¿cuál sería?",
  "Si todos los trabajos estuvieran pagados igual y requirieran el mismo tiempo de dedicación. ¿A qué te dedicarías?",
  "¿Cómo cambiarías tu vida si recibieras 1.000 euros al mes sin ninguna condición?",
  "¿Cuál es la lección más dura que has aprendido en el amor?",
  "¿Cuál de los rasgos de personalidad de tus padres quieres conservar/dejar ir?",
  "¿Hay algún sentimiento que eches de menos?",
  "¿Qué estereotipos crees que se han creado sobre ti?",
  "¿Qué pregunta estás intentando responder más en tu vida ahora mismo?",
  "¿Por qué quieres dejar de pedir perdón?",
  "¿Qué es lo mejor que has hecho por tu salud mental recientemente?",
  "¿Qué es lo que tu yo más joven no creería sobre tu vida actual?",
  "¿En qué estás pensando demasiado ahora mismo?",
  "¿Hay alguien que haya cambiado tu vida pero que no lo sepa?",
"¿Cuál de tus errores te ha enseñado más este último año?",
  "¿Qué es lo más inexplicable que te ha ocurrido?",
  "¿Cuándo fue la última vez que una decisión que tomaste cambió completamente tu vida? ¿Por qué tomaste esa decisión?",
  "¿Cuál le gustaría que fuera el título de su autobiografía?",
  "¿Qué título le pondrías a este capítulo de tu vida?",
  "¿Qué lección te llevó más tiempo desaprender?",
  "¿Qué lecciones sobre la amistad has aprendido?",
  "¿Qué es lo que antes te parecía una pérdida de tiempo y ahora consideras realmente valioso?",
  "¿Preferirías ganar inmunidad contra las enfermedades mentales o físicas?",
  "Cuando eras niño, ¿qué te asustaba de crecer?",
  "¿Cuál es un hito infravalorado de la edad adulta?",
  "¿Qué es lo que más le satisface de su trabajo actual?",
  "¿Qué proyecto paralelo te gustaría llevar a cabo si tuvieras más tiempo o recursos?",
  "¿Qué habilidad le gustaría aprender?",
  "¿Qué preguntas te hacen con demasiada frecuencia?",
  "Cuando eras niño, ¿qué era lo que los mayores no entendían de ti?",
  "Si un actor o actriz tuviera que interpretarle en una película, ¿qué le resultaría más difícil del papel?",
  "¿Qué papel desempeñabas en tu familia cuando crecías?",
  "¿Qué hay en su cultura con lo que le resulta difícil conectar?",
  "¿Cuál es tu sonido favorito?",
  "¿Cuál es tu olor favorito?",
  "¿Qué defectos te resulta más fácil aceptar: los tuyos o los de tus amigos/pareja?",
  "¿Sientes que siempre puedes elegir?",
  "¿Puede una persona cambiar simplemente decidiendo hacerlo?",
  "En nuestra sociedad, ¿quién debería cobrar más y quién menos?",
  "¿Qué tienen en común todos tus amigos?",
  "¿Qué significa para ti 'actuar según tu edad' y sientes que 'actúas según tu edad'?",
  "¿Qué es algo de tu generación que a la generación siguiente le costaría entender?",
  "¿Qué es lo que a la generación anterior le cuesta entender de tu generación?",
  "¿Qué es lo que haces o crees que algunas personas podrían considerar egoísta?",
  "¿Qué es algo que esperas y temes que nunca ocurra?",
  "¿En qué circunstancias te gustan los cambios?",
  "¿Qué animal te gustaría ser por un día?",
  "¿Cómo suena la voz dentro de tu cabeza?",
  "Piensa en quién eras hace diez años. ¿En qué aspectos te da vergüenza tu yo más joven?",
  "Rellena el espacio en blanco: siento que soy el único al que ___ no le hace gracia",
  "¿De qué manera te ha juzgado la gente antes de conocerte?",
  "¿Cuál es la inseguridad que, para bien o para mal, ha dado forma a lo que eres hoy?",
  "¿Cuál sería tu papel en un mundo sin electricidad?",
  "¿Cómo cambiarías tu forma de vivir si supieras la fecha de tu muerte?",
  "¿Cuál es el tema al que le gustaría que las noticias prestaran más atención?",
  "¿Qué pensamientos le quitan el sueño actualmente?",
  "¿Qué tienen en común todas tus ambiciones, aficiones e intereses?",
"¿Cuál es un consejo que no es tan útil como la gente cree?",
  "Rellena el espacio en blanco: Si ___ nunca hubiera sucedido, ahora estaría mucho mejor",
  "¿Qué sueles hacer cuando te sientes abrumado por tus emociones?",
  "Si pudieras invitar a cinco personas cualesquiera a una cena. ¿Quiénes serían y por qué?",
  "¿Qué debe tener un lugar para que lo consideres tu hogar?",
  "¿Cuáles son los estereotipos más comunes sobre tu cultura y cuáles se aplican realmente a ti?",
  "Si tu vida fuera un videojuego, ¿quién sería tu jefe final?",
  "¿Qué sueño te alegró haber abandonado?",
  "¿Qué hiciste ayer que te hizo sentir bien hoy?",
  "¿Qué puedes hacer hoy para sentirte bien mañana?",
  "¿Qué animal extinguido te hubiera gustado ver más?",
  ];
  
function getRandomQuestions(num) {
  let randomQuestions = [];
  for (let i = 0; i < num; i++) {
    let randomIndex = Math.floor(Math.random() * questions.length);
    randomQuestions.push(questions[randomIndex]);
  }
  return randomQuestions;
}

function displayQuestions() {
  const questionContainer = document.getElementById("question-container");
  const randomQuestions = getRandomQuestions(1);
  questionContainer.innerHTML = "";
  randomQuestions.forEach(function(question) {
    const questionElement = document.createElement("p");
    questionElement.textContent = question;
    questionContainer.appendChild(questionElement);
  });
}

window.addEventListener("load", function() {
  displayQuestions();
});

document.getElementById('refresh-btn').addEventListener('click', function() {
    location.reload();
});
