const questions = [ 
  "Quelles sont vos différentes identités ?",
  "Quel est le rituel que vous avez et dont vous ne voudriez pas vous passer ?",
  "Quel événement historique auriez-vous voulu voir se dérouler ?",
  "Quels inconvénients votre vie personnelle présenterait-elle si nous passions d'un système basé sur l'argent à un système basé sur la nature ?",
  "Quelles sont les limites de votre liberté personnelle ?",
  "Comment faites-vous face aux contradictions ?",
  "Votre bonheur individuel importe-t-il plus que le bonheur collectif des personnes qui vous entourent ?",
  "Quelle est votre part de responsabilité dans vos décisions ? Est-ce la même chose pour toutes vos décisions ?",
  "Pourquoi les gens aiment-ils se regarder les uns les autres ?",
  "Pourquoi les gens aiment-ils se regarder les uns les autres ?", "Que faut-il pour que les gens se souviennent de choses spécifiques ?",
  "D'où venez-vous et où voulez-vous aller ?",
  "Pourquoi aimez-vous dépenser de l'argent ?",
  "Pourquoi les gens ont-ils besoin d'art ?",
  "Que signifie pour vous 's'amuser ?",
  "Préférez-vous que les gens qui vous entourent soient principalement amicaux ou principalement intelligents ?",
  "Aimeriez-vous vivre dans un monde d'honnêteté radicale ?",
  "Quel est le défi que vous aimeriez le plus relever ?",
  "Qu'est-ce qui vous rend heureux ?",
  "Comment aimez-vous le plus procrastiner ?",
  "Que feriez-vous avec 10 000 euros avant qu'ils ne perdent leur valeur ?",
  "Avec quoi aimeriez-vous être payé au lieu de l'argent ?",
  "Aimeriez-vous être célèbre ? De quelle manière ?",
  "Avant de passer un appel téléphonique, vous arrive-t-il de répéter ce que vous allez dire ? Pourquoi ?",
  "Qu'est-ce qu'une journée parfaite pour vous ?",
  "Avez-vous une intuition secrète sur la façon dont vous allez mourir ?",
  "Si vous pouviez changer quoi que ce soit à la façon dont vous avez été élevé, qu'est-ce que ce serait ?",
  "Si vous pouviez vous réveiller demain en ayant acquis une qualité ou une capacité, quelle serait-elle ?",
  "Si vous pouviez poser une question sur votre avenir et obtenir une réponse, quelle serait cette question ?",
  "Quel est le plus grand accomplissement de votre vie ?",
  "Qu'est-ce que vous appréciez le plus dans une amitié ?",
  "Quel est votre souvenir le plus précieux ?",
  "Quel est votre souvenir le plus terrible ?",
  "Si vous saviez que vous mourrez dans un an, changeriez-vous votre façon de vivre ?",
  "Remplissez le blanc : j'aimerais avoir quelqu'un avec qui je pourrais partager ___.",
  "Quand avez-vous pleuré pour la dernière fois devant une autre personne ? Tout seul ?",
  "Qu'est-ce qui est trop sérieux pour être plaisanté ?",
  "Si vous deviez mourir ce soir sans avoir eu l'occasion de communiquer avec qui que ce soit, que regretteriez-vous le plus de ne pas avoir dit à quelqu'un ? Pourquoi ne l'avez-vous pas encore dit ?",
  "Votre maison/chambre, contenant tout ce que vous possédez, prend feu. Après avoir sauvé votre famille et vos animaux de compagnie, vous pouvez encore sauver un objet des flammes ? Qu'est-ce que ce serait ?",
  "Quelle chanson vous donne immédiatement envie de danser ?",
  "Qu'est-ce qui vous fait toujours rire ?",
  "Quel est le meilleur livre que vous ayez jamais lu et pourquoi ?",
  "Quel est le meilleur film que vous ayez jamais regardé et pourquoi ?",
  "Quel est l'endroit que vous préférez dans votre ville ?",
  "Quelle est la chose la plus spontanée que vous ayez jamais faite ?",
  "Quelles sont les trois choses qui vous mettent immédiatement de mauvaise humeur ?",
  "Quelles ont été vos vacances les plus excitantes ?",
  "Quelle est votre citation préférée ?",
  "Qui enviez-vous le plus et pourquoi ?",
  "Quelle est la leçon de vie la plus utile que vous ayez apprise récemment ?",
  "Qu'est-ce qui vous vient à l'esprit en premier lieu lorsque vous pensez à votre famille ?",
  "Y a-t-il une chose en laquelle vous croyez fermement ?",
  "Quelle est la chose pour laquelle vous êtes reconnaissant aujourd'hui ?",
  "Quelle est la chose qui vous enthousiasme en ce moment ?",
  "Quelle est la vertu dont vous voulez faire preuve demain ?",
  "Quelle est la chose que vous évitez ?",
  "Quelles ont été vos plus grandes victoires de la journée ?",
  "Avez-vous eu des prises de conscience importantes aujourd'hui ?",
  "Quel est le principal obstacle à la réalisation de votre prochain objectif ? Pourquoi n'y travaillez-vous pas aujourd'hui ?",
  "Si vous répétiez toutes les actions que vous avez entreprises aujourd'hui pendant un an, où aboutiriez-vous ? Est-ce l'endroit où vous voulez être ?",
  "Comment aimez-vous rendre les autres heureux ?",
  "Que feriez-vous avec 1 million d'euros en liquide ?",
  "Trois livres que vous liriez pour le reste de votre vie",
  "Si vous vivez dans un monde où chaque décision que vous prenez crée un nouvel univers parallèle : Quels sont les univers parallèles dans lesquels vous souhaiteriez le plus voyager ?",
  "Imaginez qu'entre la vie et la mort, vous vous rendiez à l'endroit où vous vous êtes senti le plus épanoui et le plus en sécurité et que vous parliez à la personne qui vous a le plus aidé à grandir dans votre enfance : Quel serait l'endroit où vous vous trouveriez et quelle serait la personne que vous rencontreriez ?",
  "Quel est l'aliment pour lequel vous avez l'attachement émotionnel le plus fort ? Pourquoi ?",
  "Quel est le concert auquel vous avez assisté le plus souvent ?",
  "Si vous pouviez essayer n'importe quel travail pendant une journée, quel serait-il ?",
  "Si tous les emplois étaient payés de la même manière et exigeaient le même engagement en termes de temps, que feriez-vous ? Que feriez-vous ?",
  "Comment changeriez-vous votre vie si vous receviez 1 000 euros par mois sans aucune condition ?",
  "Quelle est la leçon la plus difficile que vous ayez apprise en amour ?",
  "Quel trait de personnalité de vos parents voulez-vous garder/laisser tomber ?",
  "Y a-t-il un sentiment qui vous manque ?",
  "Quels sont les stéréotypes qui ont été véhiculés à votre sujet ?",
  "Quelle est la question à laquelle vous essayez le plus de répondre dans votre vie en ce moment ?",
  "De quoi voulez-vous arrêter de vous excuser ?",
  "Quelle est la meilleure chose que vous ayez faite récemment pour votre santé mentale ?",
  "Qu'est-ce que votre jeune moi ne croirait pas à propos de votre vie aujourd'hui ?",
  "Qu'est-ce que vous pensez trop en ce moment ?",
  "Y a-t-il quelqu'un qui a changé votre vie sans que vous le sachiez ?",
  "Laquelle de vos erreurs vous a le plus appris au cours de l'année écoulée ?",
  "Quelle est la chose la plus inexplicable qui vous soit arrivée ?",
  "Quelle est la dernière fois qu'une décision que vous avez prise a complètement changé votre vie ? Pourquoi avez-vous pris cette décision ?",
  "Quel titre voudriez-vous donner à votre autobiographie ?",
  "Quel titre donneriez-vous à ce chapitre de votre vie ?",
  "Quelle est la leçon que vous avez mis le plus de temps à désapprendre ?",
  "Quelles leçons sur l'amitié avez-vous apprises ?",
  "Quelle est la chose que vous considériez autrefois comme une perte de temps et que vous jugez aujourd'hui très précieuse ?",
  "Préférez-vous être immunisé contre les maladies mentales ou physiques ?",
  "Quand vous étiez enfant, qu'est-ce qui vous effrayait à l'idée de grandir ?",
  "Quelle est une étape sous-estimée de l'âge adulte ?",
  "Quelle est la partie la plus satisfaisante de votre travail actuel ?",
  "Quel projet secondaire aimeriez-vous poursuivre si vous aviez plus de temps ou de ressources ?",
  "Quelle est la compétence que vous aimeriez acquérir ?",
  "Quelles sont les questions que l'on vous pose trop souvent ?",
  "Quand vous étiez enfant, qu'est-ce que les adultes dans votre vie ne comprenaient pas à votre sujet ?",
  "Si un acteur/une actrice devait jouer votre rôle dans un film, qu'est-ce qu'il/elle trouverait le plus difficile dans ce rôle ?",
  "Quel rôle jouiez-vous dans votre famille lorsque vous étiez enfant ?",
  "Quel est l'élément de votre culture avec lequel vous avez du mal à vous identifier ?",
  "Quel est votre son préféré ?",
  "Quelle est votre odeur préférée ?",
  "Quels sont les défauts que vous avez le plus de mal à accepter : les vôtres ou ceux de vos amis/partenaires ?",
  "Avez-vous l'impression d'avoir toujours le choix ?",
  "Une personne peut-elle changer simplement en décidant de le faire ?",
  "Dans notre société, qui devrait être payé plus et qui devrait être payé moins ?",
  "Qu'est-ce que tous vos amis ont en commun ?",
  "Que signifie pour vous 'faire son âge' et avez-vous l'impression de 'faire votre âge' ?",
  "Quelle est la chose de votre génération que la génération suivante aurait du mal à comprendre ?", 
  "Quelle est la chose que la génération précédente trouve difficile à comprendre ?",
  "Qu'est-ce que la génération précédente a du mal à comprendre à propos de votre génération ?",
  "Quelle est la chose que vous faites ou croyez que certaines personnes pourraient considérer comme égoïste ?",
  "Quelle est la chose que vous espérez et dont vous craignez qu'elle ne se produise jamais ?",
  "Dans quelles circonstances aimez-vous le changement ?",
  "Quel animal souhaiteriez-vous être pendant une journée ?",
  "A quoi ressemble la voix dans votre tête ?", "A quoi ressemble la voix dans votre tête ?", "A quoi ressemble la voix dans votre tête ?",
  "Pensez à la personne que vous étiez il y a dix ans. De quelle manière votre jeune moi vous fait-il grimacer ?",
  "Remplissez le blanc : j'ai l'impression d'être le seul à ne pas trouver ___ drôle",
  "De quelle manière les gens vous ont-ils jugé avant d'apprendre à vous connaître ?",
  "Quelle est l'insécurité qui, pour le meilleur ou pour le pire, a façonné la personne que vous êtes aujourd'hui ?",
  "Quel serait votre rôle dans un monde sans électricité ?",
  "Comment changeriez-vous votre façon de vivre si vous connaissiez la date de votre mort ?",
  "Quelle est la question à laquelle vous souhaiteriez que les journaux télévisés accordent plus d'attention ?",
  "Quelles sont les pensées qui vous empêchent de dormir la nuit ?",
  "Quel est le point commun entre vos ambitions, vos loisirs et vos centres d'intérêt ?",
  "Quel est le conseil qui n'est pas aussi utile que les gens le pensent ?",
  "Remplissez le blanc : si ___ n'était jamais arrivé, je serais dans une bien meilleure situation en ce moment",
  "Qu'avez-vous tendance à faire lorsque vous êtes submergé par vos émotions ?",
  "Si vous pouviez inviter cinq personnes à un dîner. Qui serait-ce et pourquoi ?",
  "Qu'est-ce qu'un lieu doit avoir pour que vous le considériez comme votre maison ?",
  "Quels sont les stéréotypes courants sur votre culture et lesquels s'appliquent réellement à vous ?",
  "Si votre vie était un jeu vidéo, qui serait votre dernier patron ?",
  "Quel est le rêve que vous êtes heureux d'avoir abandonné ?",
  "Quelle est la chose que vous avez faite hier et qui vous a fait du bien aujourd'hui ?",
  "Quelle est la chose que vous pouvez faire aujourd'hui et qui vous fera vous sentir bien demain ?",
  "Quel est l'animal éteint que vous auriez voulu voir le plus souvent ?",
  ] ;

  
function getRandomQuestions(num) {
  let randomQuestions = [];
  for (let i = 0; i < num; i++) {
    let randomIndex = Math.floor(Math.random() * questions.length);
    randomQuestions.push(questions[randomIndex]);
  }
  return randomQuestions;
}

function displayQuestions() {
  const questionContainer = document.getElementById("question-container");
  const randomQuestions = getRandomQuestions(1);
  questionContainer.innerHTML = "";
  randomQuestions.forEach(function(question) {
    const questionElement = document.createElement("p");
    questionElement.textContent = question;
    questionContainer.appendChild(questionElement);
  });
}

window.addEventListener("load", function() {
  displayQuestions();
});

document.getElementById('refresh-btn').addEventListener('click', function() {
    location.reload();
});
