const questions = [ 
  "Was sind einige Ihrer verschiedenen Identitäten?",
  "Welches Ritual haben Sie, auf das Sie nicht verzichten möchten?",
  "Welches historische Ereignis hätten Sie gerne miterlebt?",
  "Welche Nachteile hätte Ihr persönliches Leben, wenn wir von einem geldbasierten System zu einem naturbasierten System übergehen würden?",
  "Wo liegen die Grenzen Ihrer persönlichen Freiheit?",
  "Wie gehen Sie mit Widersprüchen um?",
  "Ist Ihr individuelles Glück wichtiger als das kollektive Glück der Menschen um Sie herum?",
  "Wie viel Verantwortung übernehmen Sie für Ihre Entscheidungen? Ist sie für alle Ihre Entscheidungen gleich groß?",
  "Warum sehen sich die Menschen gerne an?",
  "Was braucht es, damit sich Menschen an bestimmte Dinge erinnern?",
  "Woher kommen Sie und wohin wollen Sie?",
  "Wofür geben Sie gerne Geld aus?",
  "Wozu brauchen Menschen Kunst?",
  "Was bedeutet 'Spaß haben' für Sie?",
  "Würden Sie es vorziehen, dass die Menschen um Sie herum hauptsächlich freundlich oder hauptsächlich intelligent sind?",
  "Würden Sie gerne in einer Welt der radikalen Ehrlichkeit leben",
  "Welcher Herausforderung würden Sie sich am liebsten stellen?",
  "Was macht Sie glücklich?",
  "Wie prokrastinieren Sie am liebsten?",
  "Was würden Sie mit 10.000€ machen, bevor sie wertlos werden?",
  "Womit würden Sie gerne statt mit Geld bezahlt werden?",
  "Würden Sie gerne berühmt sein? Auf welche Weise?",
  "Üben Sie manchmal vor einem Telefonat, was Sie sagen werden? Warum?",
  "Wie würde ein perfekter Tag für Sie aussehen?",
  "Haben Sie eine geheime Ahnung, wie Sie sterben werden?",
  "Wenn Sie etwas an Ihrer Erziehung ändern könnten, was wäre das?",
  "Wenn Sie morgen aufwachen könnten und eine Eigenschaft oder Fähigkeit gewonnen hätten, welche wäre das?",
  "Wenn Sie eine Frage zu Ihrer Zukunft stellen könnten und eine Antwort bekämen, wie würde diese Frage lauten?",
  "Was ist die größte Errungenschaft in Ihrem Leben?",
  "Was schätzen Sie am meisten an einer Freundschaft",
  "Was ist deine schönste Erinnerung?",
  "Was ist Ihre schrecklichste Erinnerung?",
  "Wenn du wüsstest, dass du in einem Jahr sterben würdest, würdest du deine Lebensweise ändern?",
  "Füllen Sie die Lücke aus: Ich wünschte, ich hätte jemanden, mit dem ich ___ teilen könnte,",
  "Wann haben Sie das letzte Mal vor einem anderen Menschen geweint? Allein?",
  "Was, wenn überhaupt, ist zu ernst, um darüber zu scherzen?",
  "Wenn Sie heute Abend sterben würden, ohne die Möglichkeit, mit jemandem zu sprechen, was würden Sie am meisten bedauern, wenn Sie es niemandem gesagt hätten? Warum haben Sie es noch nicht gesagt?",
  "Ihr Haus/Zimmer, in dem sich alles befindet, was Sie besitzen, fängt Feuer. Nachdem Sie Ihre Familie und Ihre Haustiere gerettet haben, können Sie noch einen Gegenstand vor den Flammen retten? Was wäre das?",
  "Welches Lied bringt dich sofort zum Tanzen?",
  "Was bringt dich immer zum Lachen?",
  "Welches ist das beste Buch, das Sie je gelesen haben und warum?",
  "Welches ist der beste Film, den Sie je gesehen haben und warum?",
  "Was ist Ihr Lieblingsort in Ihrer Stadt?",
 "Was war das Spontanste, was Sie je getan haben?",
  "Bei welchen drei Dingen bekommen Sie sofort schlechte Laune?",
  "Was war Ihr aufregendster Urlaub?",
  "Welches ist Ihr Lieblingszitat?",
  "Wen beneiden Sie am meisten und warum?",
  "Was war die hilfreichste Lebenslektion, die Sie in letzter Zeit gelernt haben?",
  "Woran denken Sie zuerst, wenn Sie an Ihre Familie denken?",
  "Gibt es etwas, an das Sie fest glauben?",
  "Für welche Sache sind Sie heute dankbar?",
  "Was ist eine Sache, über die Sie sich gerade freuen?",
  "Was ist eine Tugend, die Sie morgen zeigen möchten?",
  "Was ist eine Sache, die Sie vermeiden?",
  "Was waren Ihre größten Erfolge des Tages?",
  "Hatten Sie heute irgendwelche wichtigen Erkenntnisse?",
  "Was ist der größte Engpass, um Ihr nächstes Ziel zu erreichen? Warum arbeiten Sie heute nicht daran?",
  "Wenn Sie jede Handlung, die Sie heute vorgenommen haben, ein Jahr lang wiederholen würden, wo würden Sie dann landen? Ist das der Ort, an dem Sie sein wollen?",
  "Wie machen Sie andere gerne glücklich?",
  "Was würden Sie jetzt mit 1 Million € in bar tun?",
  "Drei Bücher, die du für den Rest deines Lebens lesen würdest?",
  "Wenn Sie in einer Welt leben, in der jede Entscheidung, die Sie treffen, ein neues Paralleluniversum erschafft: Welche Paralleluniversen würdest du am liebsten bereisen wollen?",
  "Stellen Sie sich vor, Sie würden zwischen Leben und Tod den Ort besuchen, an dem Sie sich am meisten erfüllt und am sichersten gefühlt haben, und mit der Person sprechen, die Ihnen in Ihrer Kindheit am meisten geholfen hat, zu wachsen: An welchem Ort würden Sie sich befinden und welche Person würden Sie treffen?",
  "Zu welchem Lebensmittel haben Sie die stärkste emotionale Bindung? Warum?",
  "Welches war Ihr Lieblingskonzert, das Sie besucht haben?",
  "Wenn Sie einen Tag lang einen beliebigen Job ausprobieren könnten, welcher wäre das?",
  "Wenn alle Jobs gleich bezahlt würden und den gleichen Zeitaufwand erfordern würden. Was würden Sie tun?",
  "Wie würdest du dein Leben verändern, wenn du 1.000€/Monat ohne Bedingungen erhalten würdest?",
  "Was ist die schwierigste Lektion, die Sie in der Liebe gelernt haben?",
  "Welchen Charakterzug Ihrer Eltern würden Sie gerne behalten oder loslassen?",
  "Gibt es ein Gefühl, das Sie vermissen?",
  "Welche Stereotypen wurden Ihrer Meinung nach über Sie verbreitet?",
  "Welche Frage versuchen Sie in Ihrem Leben gerade am meisten zu beantworten?",
  "Wofür möchten Sie sich nicht mehr entschuldigen?",
  "Was ist das Beste, was Sie in letzter Zeit für Ihre geistige Gesundheit getan haben?",
  "Was würde Ihr jüngeres Ich über Ihr heutiges Leben nicht glauben?",
  "Woran denken Sie im Moment zu viel?",
  "Gibt es jemanden, der Ihr Leben verändert hat, ohne dass Sie es wissen?",
  "Aus welchen Ihrer Fehler haben Sie im vergangenen Jahr am meisten gelernt?",
  "Was ist das Unerklärlichste, das Ihnen passiert ist?",
  "Wann war das letzte Mal, dass eine Entscheidung, die Sie getroffen haben, Ihr Leben komplett verändert hat? Warum haben Sie diese Entscheidung getroffen?",
  "Wie würde der Titel Ihrer Autobiografie lauten?",
  "Welchen Titel würden Sie diesem Kapitel Ihres Lebens geben?",
  "Welche Lektion haben Sie am längsten nicht mehr gelernt?",
"Welche Lektionen über Freundschaft haben Sie gelernt?",
  "Was ist etwas, das Sie früher für Zeitverschwendung hielten, jetzt aber für sehr wertvoll halten?",
  "Würden Sie sich lieber gegen geistige oder körperliche Krankheiten immunisieren?",
  "Was hat Ihnen als Kind Angst vor dem Erwachsenwerden gemacht?",
  "Was ist ein unterschätzter Meilenstein des Erwachsenseins?",
  "Was ist das Erfüllendste an Ihrem derzeitigen Job?",
  "Welches Nebenprojekt würden Sie gerne weiterverfolgen, wenn Sie mehr Zeit oder Ressourcen hätten?",
  "Welche Fähigkeit würden Sie gerne erlernen?",
  "Welche Fragen werden Ihnen viel zu oft gestellt?",
  "Was haben die Erwachsenen in Ihrem Leben nicht verstanden, als Sie ein Kind waren?",
  "Wenn ein Schauspieler/eine Schauspielerin Sie in einem Film spielen müsste, was fiele ihm/ihr an der Rolle am schwersten?",
  "Welche Rolle hast du in deiner Familie gespielt, als du aufgewachsen bist?",
  "Was ist etwas in Ihrer Kultur, mit dem Sie sich nur schwer identifizieren können?",
  "Welches ist Ihr Lieblingsgeräusch?",
  "Was ist Ihr Lieblingsgeruch?",
  "Welche Fehler können Sie leichter akzeptieren: Ihre eigenen oder die Ihrer Freunde/Partner?",
  "Haben Sie das Gefühl, immer die Wahl zu haben?",
  "Kann sich ein Mensch ändern, indem er sich einfach dazu entschließt?",
  "Wer sollte in unserer Gesellschaft mehr und wer weniger verdienen?",
  "Was haben alle deine Freunde gemeinsam?",
  "Was bedeutet es für dich, dich deinem Alter entsprechend zu verhalten, und hast du das Gefühl, dass du dich deinem Alter entsprechend verhältst?",
  "Was ist etwas aus Ihrer Generation, das die nächste Generation nur schwer verstehen würde?",
  "Was ist etwas, das die vorherige Generation an Ihrer Generation nicht verstehen kann?",
  "Was ist etwas, das Sie tun oder glauben, das manche Menschen als egoistisch ansehen könnten?",
  "Was ist etwas, das Sie sich wünschen und von dem Sie befürchten, dass es nie eintreten wird?",
  "Unter welchen Umständen mögen Sie Veränderungen?",
  "Welches Tier würden Sie gerne einen Tag lang sein?",
  "Wie klingt die Stimme in deinem Kopf?",
  "Denken Sie daran zurück, wer Sie vor zehn Jahren waren. Inwiefern lässt dich dein jüngeres Ich erschaudern?",
  "Füllen Sie die Lücke: Ich habe das Gefühl, dass ich der Einzige bin, der ___ nicht lustig findet",
  "Inwiefern haben dich die Leute beurteilt, bevor sie dich kennengelernt haben?",
  "Was ist eine Unsicherheit, die Sie im Guten wie im Schlechten zu dem gemacht hat, was Sie heute sind?",
  "Welche Rolle würden Sie in einer Welt ohne Strom spielen?",
  "Wie würden Sie Ihr Leben ändern, wenn Sie das Datum Ihres Todes kennen würden?",
  "Welches ist ein Thema, von dem Sie sich wünschen würden, dass es in den Nachrichten mehr Beachtung findet?",
  "Welche Gedanken halten Sie derzeit nachts wach?",
  "Was haben all Ihre Ambitionen, Hobbys und Interessen gemeinsam?",
"Was ist ein Ratschlag, der nicht so hilfreich ist, wie die Leute denken?",
  "Füllen Sie die Lücke: Wenn ___ nie passiert wäre, würde es mir jetzt viel besser gehen,",
  "Was tun Sie, wenn Sie von Ihren Gefühlen überwältigt werden?",
  "Wenn Sie fünf beliebige Personen zu einer Dinnerparty einladen könnten. Wer würde es sein und warum?",
  "Was muss ein Ort haben, damit Sie ihn als Ihr Zuhause betrachten?",
  "Was sind gängige Stereotypen über Ihre Kultur und welche davon treffen tatsächlich auf Sie zu?",
  "Wenn Ihr Leben ein Videospiel wäre, wer wäre Ihr Endgegner?",
  "Was ist ein Traum, den Sie gerne aufgegeben hätten?",
  "Was haben Sie gestern getan, das Ihnen heute ein gutes Gefühl gibt?",
  "Was können Sie heute tun, damit Sie sich morgen gut fühlen?",
  "Welches ausgestorbene Tier hättest du am liebsten gesehen?",
  ];
  
function getRandomQuestions(num) {
  let randomQuestions = [];
  for (let i = 0; i < num; i++) {
    let randomIndex = Math.floor(Math.random() * questions.length);
    randomQuestions.push(questions[randomIndex]);
  }
  return randomQuestions;
}

function displayQuestions() {
  const questionContainer = document.getElementById("question-container");
  const randomQuestions = getRandomQuestions(1);
  questionContainer.innerHTML = "";
  randomQuestions.forEach(function(question) {
    const questionElement = document.createElement("p");
    questionElement.textContent = question;
    questionContainer.appendChild(questionElement);
  });
}

window.addEventListener("load", function() {
  displayQuestions();
});

document.getElementById('refresh-btn').addEventListener('click', function() {
    location.reload();
});
